#!/bin/sh
# Start/stop the silc daemon.
#
# Very simple init script, distribution agnostic
#
### BEGIN INIT INFO
# Provides:             silcd
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:	
# Short-Description:    silcd
### END INIT INFO

TEMP=/opt/silc-1.1.18/var/
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/silc-1.1.18/sbin
DESC="silcd daemon"
NAME=silcd
DAEMON=silcd
CONFIG_FILE=/opt/silc-1.1.18/etc/silcd.conf

PIDFILE="${TEMP}/${NAME}.pid"

#. /lib/lsb/init-functions

case "$1" in
  start|"")
#	log_daemon_msg "Starting silcd server" "silcd"
#	start_daemon -P $PIDFILE $DAEMON -f ${CONFIG_FILE}
	$DAEMON -f ${CONFIG_FILE} 2>&1 >/tmp/LOG2
#	log_end_msg $?
	sleep 3
	;;
  restart|reload|force-reload)
	echo "Reloading..."
	pkill -F ${PIDFILE} -SIGHUP
	exit 3
	;;
  stop)
	echo "Stopping..."
	pkill -F ${PIDFILE}
	rm -f ${PIDFILE}
	;;
  status)
	echo "Status..."
	ls -l ${PIDFILE}
	exit $?
	;;
  *)
	echo "Usage: silcd [start|stop|status]" >&2
	exit 3
	;;
esac
